Custom cache key
Baseflow/flutter_cached_network_image pull request #490
Opened 2020-10-26 20:06 UTC by hvasc

### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)
feature

### :arrow_heading_down: What is the current behavior?
The library is not support dynamic url like cloud front's secure url

### :new: What is the new behavior (if this is a feature change)?
support flutter_cache_manager 2.0.0 in Added option for a key different from the url.
Can use parameter cacheKey. if use static url, just use same.

### :boom: Does this PR introduce a breaking change?
No

### :bug: Recommendations for testing
Use CDN security url

### :memo: Links to relevant issues/docs
https://github.com/Baseflow/flutter_cached_network_image/issues/488
https://github.com/Baseflow/flutter_cached_network_image/issues/428
https://github.com/Baseflow/flutter_cache_manager/pull/179

### :thinking: Checklist before submitting

- [x] All projects build
- [x] Follows style guide lines ([code style guide](https://github.com/Baseflow/flutter_cached_network_image/blob/develop/CONTRIBUTING.md))
- [x] Relevant documentation was updated
- [x] Rebased onto current develop

2020-10-27 13:37 UTC, renefloor commented
Thanks. If I'm correct the flutter_cache_manager dependency needs to be increased to at least `^2.0.0`?

2020-10-27 22:23 UTC, hvasc commented
> Thanks. If I'm correct the flutter_cache_manager dependency needs to be increased to at least `^2.0.0`?

Yes, I’ll change it.

2020-11-07 04:46 UTC, huanghui1998hhh commented
Maybe there's something wrong with my way to use the cacheKey,but it seems not work.My code is like this,
```
CachedNetworkImage(
            cacheKey: 'test111',
            imageUrl: getUrl(),
            placeholder: (context, url) => CircularProgressIndicator(),
            errorWidget: (context, url, error) => Icon(Icons.error),
          ),
```
First,run it normally.Then change the imageUrl and turn off the network,the results show that it still use the url as cache key.
I think maybe my wrong,so could you give me some documentation.

2020-11-07 09:55 UTC, hvasc commented
> Maybe there's something wrong with my way to use the cacheKey,but it seems not work.My code is like this,
> 
> ```
> CachedNetworkImage(
>             cacheKey: 'test111',
>             imageUrl: getUrl(),
>             placeholder: (context, url) => CircularProgressIndicator(),
>             errorWidget: (context, url, error) => Icon(Icons.error),
>           ),
> ```
> 
> First,run it normally.Then change the imageUrl and turn off the network,the results show that it still use the url as cache key.
> I think maybe my wrong,so could you give me some documentation?

I missed cacheKey in CachedNetworkImageProvider's constructor.
fixed it. thank you very much.
If more wrong feature, let me know please.

2020-11-09 04:48 UTC, huanghui1998hhh commented
It work,thanks!

2020-11-12 18:09 UTC, oswaldocueto01 commented
Please add this feature asap...

2020-11-19 13:27 UTC, renefloor requested changes
One minor issue, but otherwise LGTM!

2020-11-19 13:27 UTC, renefloor commented on lib/src/image_provider/_image_provider_io.dart
> +      }
We should do the same check as in the cachemanager, so if the key is not set use the url as key. If one of the keys is not set they can be different even though the url is the same.
```suggestion
      var sameKey = (cacheKey ?? url) == (other.cacheKey ?? other.url);
      return sameKey && scale == other.scale;
```

2020-11-19 13:27 UTC, renefloor commented on lib/src/image_provider/_image_provider_web.dart
> +      }
```suggestion
      var sameKey = (cacheKey ?? url) == (other.cacheKey ?? other.url);
      return sameKey && scale == other.scale;
```

2020-11-19 13:27 UTC, renefloor commented
@hvasc If you don't mind I can just commit this myself and merge the PR?

2020-11-21 02:19 UTC, hvasc commented
> If you don't mind I can just commit these suggestions myself and merge the PR?

that's cool. thanks.

2020-11-27 10:21 UTC, renefloor approved these changes

2020-11-27 10:21 UTC, merged